/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmostrassen;

import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author leeyn
 */
public class LauncherUI extends javax.swing.JFrame {

    private List<JTextField> MlistA;
    private List<JTextField> MlistB;

    /**
     * Creates new form LauncherUI
     */
    public LauncherUI() {
        initComponents();
        MlistA = new ArrayList<>();
        MlistB = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        labelB = new javax.swing.JLabel();
        txtFa = new javax.swing.JTextField();
        txtCa = new javax.swing.JTextField();
        txtFb = new javax.swing.JTextField();
        txtCb = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jPaneA = new javax.swing.JPanel();
        jPaneB = new javax.swing.JPanel();
        btnCls = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Titulo.setText("Multiplicación de Matrices Por Strassen");

        labelA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelA.setText("Matriz A");

        labelB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelB.setText("Matriz B");

        txtFb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFbActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneALayout = new javax.swing.GroupLayout(jPaneA);
        jPaneA.setLayout(jPaneALayout);
        jPaneALayout.setHorizontalGroup(
            jPaneALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        jPaneALayout.setVerticalGroup(
            jPaneALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPaneBLayout = new javax.swing.GroupLayout(jPaneB);
        jPaneB.setLayout(jPaneBLayout);
        jPaneBLayout.setHorizontalGroup(
            jPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jPaneBLayout.setVerticalGroup(
            jPaneBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnCls.setText("Limpiar");
        btnCls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClsActionPerformed(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelA)
                                .addGap(18, 18, 18)
                                .addComponent(txtFa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPaneA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaneB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(labelB)
                    .addComponent(txtFa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnCls)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPaneA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPaneB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        int fA = Integer.parseInt(txtFa.getText());
        int cA = Integer.parseInt(txtCa.getText());
        int fB = Integer.parseInt(txtFb.getText());
        int cB = Integer.parseInt(txtCb.getText());
        if (cA == fB) {
            for (int i = 0; i < fA; i++) {
                for (int j = 0; j < cA; j++) {
                    JTextField txta = new JTextField();
                    txta.setBounds(35 * j, 35 * i, 30, 30);
                    jPaneA.add(txta);
                    MlistA.add(txta);
                }
            }

            for (int i = 0; i < fB; i++) {
                for (int j = 0; j < cB; j++) {
                    JTextField txtb = new JTextField();
                    txtb.setBounds(35 * j, 35 * i, 30, 30);
                    jPaneB.add(txtb);
                    MlistB.add(txtb);
                }
            }

            jPaneA.updateUI();
            jPaneB.updateUI();
        } else {
            JOptionPane.showMessageDialog(null, "Las matrices no se pueden operar");
            txtCa.setText("");
            txtFa.setText("");
            txtCb.setText("");
            txtFb.setText("");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtFbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFbActionPerformed

    private void btnClsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClsActionPerformed

        txtCa.setText("");
        txtFa.setText("");
        txtCb.setText("");
        txtFb.setText("");

        jPaneA.removeAll();
        jPaneA.updateUI();
        jPaneB.removeAll();
        jPaneB.updateUI();
    }//GEN-LAST:event_btnClsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fA = Integer.parseInt(txtFa.getText());
        int cA = Integer.parseInt(txtCa.getText());
        int fB = Integer.parseInt(txtFb.getText());
        int cB = Integer.parseInt(txtCb.getText());

        double matrizA[][] = new double[fA][cA];
        double listamatA[] = new double[fA * cA];

        int i = 0;
        for (JTextField txta : MlistA) {
            listamatA[i] = Double.parseDouble(txta.getText());
            i++;
        }

        int countA = 0;
        for (int i1 = 0; i1 < fA; i1++) {
            for (int j1 = 0; j1 < cA; j1++) {
                matrizA[i1][j1] = listamatA[countA];
                countA++;
            }
        }

//        for(int g = 0; g<fA;g++){
//            System.out.println(" ");
//            for(int h = 0;h<cA;h++){
//                System.out.print(" "+matrizA[g][h]);
//               
//            }
//        }
        double matrizB[][] = new double[fB][cB];
        double listamatB[] = new double[fB * cB];

        int j = 0;
        for (JTextField txtb : MlistB) {
            listamatB[j] = Double.parseDouble(txtb.getText());
            j++;
        }

        int countB = 0;
        for (int i2 = 0; i2 < fB; i2++) {
            for (int j2 = 0; j2 < cB; j2++) {
                matrizB[i2][j2] = listamatB[countB];
                countB++;
            }
        }

//        for(int q = 0; q<fB;q++){
//            System.out.println(" ");
//            for(int w = 0;w<cB;w++){
//                System.out.print(" "+matrizB[q][w]);               
//            }
//        }
        AlgoritmoStrassen AS = new AlgoritmoStrassen(matrizA, matrizB, fA, cA, fB, cB);
        double [][]MR=AS.generarMAtriz();

        Resultado r = new Resultado(MR,fA,cB,AS.temporal,AS.contador);
        r.setLocationRelativeTo(this);
        r.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCls;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPaneA;
    private javax.swing.JPanel jPaneB;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelB;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtCb;
    private javax.swing.JTextField txtFa;
    private javax.swing.JTextField txtFb;
    // End of variables declaration//GEN-END:variables
}
